{{ config(
    materialized = 'table',
    engine = 'MergeTree()',
    order_by = ['order_purchase_date', 'order_id'],
    partition_by = ['toYYYYMM(order_purchase_date)']
) }}

select
    o.order_id,
    o.customer_id,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    c.customer_region,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_purchase_date,
    o.order_purchase_month,
    o.order_approved_at,
    o.order_approved_date,
    o.order_delivered_carrier_date,
    o.order_delivered_carrier_date_day,
    o.order_delivered_customer_date,
    o.order_delivered_customer_date_day,
    o.order_estimated_delivery_date,
    o.order_estimated_delivery_date_day,
    o.is_delivered,
    o.is_canceled,
    o.is_unavailable,
    o.actual_delivery_days,
    o.estimated_delivery_days,
    o.delivery_delay_days,
    o.is_late_delivery,
    o.item_count,
    o.unique_product_count,
    o.unique_seller_count,
    o.order_item_value,
    o.order_freight_value,
    o.order_total_value,
    o.payment_count,
    o.payment_types,
    o.max_payment_installments,
    o.payment_value,
    o.credit_card_value,
    o.boleto_value,
    o.voucher_value,
    o.debit_card_value,
    o.review_count,
    o.avg_review_score,
    o.latest_review_id,
    o.latest_review_score,
    o.latest_review_creation_date,
    o.latest_review_answer_timestamp,
    o.has_review_comment
from {{ ref('int_orders_enriched') }} as o
left join {{ ref('dim_customers') }} as c
    on o.customer_id = c.customer_id
