version: 2

macros:
  - name: test_non_negative
    description: "Generic test. Fails when a numeric column has a value lower than zero."
    arguments:
      - name: model
        type: string
      - name: column_name
        type: string

  - name: test_unique_combination
    description: "Generic test. Fails when a combination of columns is not unique."
    arguments:
      - name: model
        type: string
      - name: combination_of_columns
        type: list
